### ISSUE TITLE
Starting from first bag when sort items

### ISSUE THREAD

**Issue by azmanomer** [shirsig/SortBags#10]
When i click sort items it starts from my first bag this started yesterday :(

**Comment by shirsig** [comment]
/run SetSortBagsRightToLeft(false)
(or true)

**Comment by azmanomer** [comment]
Thank you for reply but if writing this ingame should have fix it. its not working :(

**Comment by azmanomer** [comment]
oh i found the problem im using button also when i type /run SortBags() its sorting correctly but when i click button its ignoring my decision

**Comment by shirsig** [comment]
Then it's some other addon's button. This doesn't come with any buttons and Cleanup's button just calls this.

**Comment by azmanomer** [comment]
using https://github.com/shirsig/Cleanup this one for button with bagnon addon

**Comment by azmanomer** [comment]
sorry bagnon overwrite the sorting i found the fix
