### ISSUE TITLE
Errors out when sorting the Bank

### ISSUE THREAD

**Issue by cubano100pct** [shirsig/SortBags#11]
Errors out when sorting the Bank.  Tried with Bagon, Cumbutor and with standard bags. This is the error I got I removed all bag managers. Just standard bag.

Date: 2019-09-18 23:31:00
ID: 1
Error occured in: Global
Count: 1
Message: [string "SortBankBag()"] line 1:
   attempt to call global 'SortBankBag' (a nil value)
Debug:
   [string "SortBankBag()"]:1: in main chunk
   [C]: RunScript()
   ..\FrameXML\ChatFrame.lua:2033: ?()
   ..\FrameXML\ChatFrame.lua:4609: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4270: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:2699:
      ..\FrameXML\ChatFrame.lua:2692
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:338: handler()
   ..\FrameXML\SecureTemplates.lua:616: SecureActionButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'SortBankBag' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLootClassic, vv1.1.12
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DungeonFinder, v0.1.5
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  GatherMate2, v1.45
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v4.1.1 BETA
  Recount, vv1.13.2c
  Scrap, v13.19
  ScrapSpotlight, v13.19
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SortBags, v0.1.2
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomCats, v0.0.2
  TomTom, vv11302-1.0.7
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=42e)

**Comment by shirsig** [comment]
It's SortBankBags (plural)
