### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by MightBeChris** [shirsig/SortBags#12]
I try to run every command you list in Classic and it has zero results.  No error messages either.

**Comment by shirsig** [comment]
Did you check if the addon is even loaded? Maybe you didn't rename the addon folder properly. The folder must always have the same name as the .toc file.

**Comment by MightBeChris** [comment]
The addon is enabled.
https://photos.app.goo.gl/yiHshCxgKRYcXRgK9
I am typing /run SortBags().  Are there any known addon conflicts?

**Comment by shirsig** [comment]
Could be, though no one's ever reported any. I don't think it's very likely but then I can't think of anything else.

**Comment by MightBeChris** [comment]
Ok.  Wierd.  I'll double check everything.  Thanks for taking a look.

Update: I put the command in a macro and it works.  Doesn't work when I paste the same line into my chat edit box though.  So maybe it's conflicting with Prat?  It shouldn't since the macro is sending the same action as my typing it, right?  But it works from the macro.  So weird but thought you'd be interested.  Feel free to close this?

**Comment by shirsig** [comment]
Thanks for the update. It must be some sort of addon conflict because for me it works fine from the chat.
