### ISSUE TITLE
Random bag slots not filed / ignored

### ISSUE THREAD

**Issue by Sven-Massard** [shirsig/SortBags#14]
When I do "/run SortBags()" it always leaves empty spaces
Tried to disable all other addons, same result
![WoWScrnShot_081020_023608](https://user-images.githubusercontent.com/45073305/89745330-6105e980-dab3-11ea-9252-bfc429692489.jpg)
![WoWScrnShot_081020_023516](https://user-images.githubusercontent.com/45073305/89745331-62371680-dab3-11ea-8c57-d3b3d0e152e2.jpg)
![WoWScrnShot_081020_023222](https://user-images.githubusercontent.com/45073305/89745332-62cfad00-dab3-11ea-9c7e-71f1754c90ec.jpg)

**Comment by shirsig** [comment]
I don't understand, what's random about this? Where else would you expect the empty slots to be? I have noticed weird behavior shortly after zoning in sometimes which I still need to investigate but I don't see that in those pictures.

**Comment by Sven-Massard** [comment]
It took me some time to understand that bags in this addon are sorted from bottom to top. Maybe there is an option to change it. I will look at it. Not a bug, sorry.
