### ISSUE TITLE
SortBags tries to put primals and motes into enchanting bag

### ISSUE THREAD

**Issue by Sven-Massard** [shirsig/SortBags#18]
![WoWScrnShot_061621_180556](https://user-images.githubusercontent.com/45073305/122254631-92b6c080-cecd-11eb-8734-c26f49608a03.jpg)
Also happens when bag is bag slot instead of on bank

**Comment by shirsig** [comment]
But they do fit in it right? I got the lists for that from wowhead. It will put as many items that fit into the special bags as possible to optimize bag space.

**Comment by Sven-Massard** [comment]
I am surprised as you are, but they do not (currently). Tried it manually.

**Comment by shirsig** [comment]
well, I can remove them. They're also on the lists for all the other special bags I think. Do you know if they can't go there either? And if it applies to other items besides motes and primals? There's a surprisingly large number of seemingly unrelated items on those wowhead lists.

**Comment by shirsig** [comment]
https://wowwiki-archive.fandom.com/wiki/Enchanting_bags "As of Patch 2.3, these bags can now carry oil, elemental essences, motes, primals, and other items made through enchanting, including rods." looks like it's a blizzard bug. I've removed the motes and primals, hope these are the only ones affected.

**Comment by Sven-Massard** [comment]
Oil does not go into the enchanting bag either currently. Your addon has is it right. Works perfectly now, thanks for fixing.
