### ISSUE TITLE
Locking items in bag

### ISSUE THREAD

**Issue by EffToyz** [shirsig/SortBags#2]
Using Clean_up with pfUI, pretty often after sorting bags I got some items locked up until some time passed or relog.
Not sure which addon this issue is exactly, gonna report to pfUI as well.
![cleanupbug](https://cloud.githubusercontent.com/assets/24850811/21829579/e7645f12-d764-11e6-8922-e636238e93bf.PNG)

**Comment by shirsig** [comment]
don't, just upvote here: https://elysium-project.org/bugtracker/issue/966

**Comment by EffToyz** [comment]
Oh, I see now. Thanks, voted. Any change to add delay in sorting for now until bug has fixed?

**Comment by shirsig** [comment]
It seems even with a quite significant delay it still happens. Not sure what's causing it exactly.
