### ISSUE TITLE
Issue with Mining Bag sorting.

### ISSUE THREAD

**Issue by Verlash** [shirsig/SortBags#24]
The game allows Motes and Primals of Earth and Fire to go in Mining Bags, however it appears that SortBags does not know this, sorting will never put them in the Mining bag, but if you have them in the bag when you sort, then they will be pulled out of the Mining bag and sorted into normal bags.
Link to video recording of the issue: [https://youtu.be/rF_E77ki1M4](https://youtu.be/rF_E77ki1M4)

**Comment by Verlash** [comment]
To clarify, this is on Wrath Classic 3.4.1

**Comment by shirsig** [comment]
There was a bug with items which can go in multiple types of special bags. Can you try again with the latest version please?

**Comment by Verlash** [comment]
Just got home and tried with the latest version. it works now.
