### ISSUE TITLE
Items greyed out after sorting bags

### ISSUE THREAD

**Issue by Finrodi** [shirsig/SortBags#4]
Hey.. I have the problem that somtimes, when I sort my bags with the addon, that some items are greyed out and not usuable at all. I cannot use them and I cant switch them around either. Only a relog helps.

Other than that I love this and all your other addons! :)

**Comment by shirsig** [comment]
https://github.com/shirsig/Clean_Up/issues/2 it's a server bug. you can upvote it on the tracker (maybe if they no longer use the nost core like they said it will be gone nayway)

**Comment by MarkusNemesis** [comment]
I'd like to re-open this one. It is apparently fixable by inserting a delay in the loop so that it sorts slower. A  delay of .25 seconds should resolve it. Otherwise, make it an adjustable variable and we can tune to taste. @shirsig

**Comment by Finrodi** [comment]
Any idea where to add the delay @MarkusNemesis ? :p

**Comment by MarkusNemesis** [comment]
That's the issue, I don't know... @shirsig plz

**Comment by shirsig** [comment]
I posted a way to add a delay once in some issue or thread but dont remember where, couldve been an issue in the pfui repo.
Unfortunately the delay had to be so large that I find it more practical to relog.
Ill try to dig it up when i have time or come up with a new one. In any case, this is still a server bug and should be fixed there ideally. Do you know if it has been reported? I reported it on various nost and successor bugtrackers but they might have been lost in the drama.

**Comment by Finrodi** [comment]
Found out how:
Line 269 return instead of break
Line 139 0.3 seems to work for me, otherwise up it.

You say its more practical to relog but once the addon has to sort quite a few amount of item it always bugs without delay (due to server) so for me adding a delay is way more practical. Thanks for the addon!
