### ISSUE TITLE
Getting items Greyed out after useing sortbag.

### ISSUE THREAD

**Issue by rex099** [shirsig/SortBags#6]
So this happens quite often after clicking the  sort bag icon with pfui I get items being grayed out and they are unable to be moved/used until restarting the client. 

If you look here you can see the scroll is grayed out.

![wom1jpk 1](https://user-images.githubusercontent.com/26062878/35886545-5df95068-0b5f-11e8-8f11-540ce4cff316.png)

**Comment by shirsig** [comment]
https://github.com/shirsig/SortBags/issues/4
